# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccbar < Formula
  desc "A beautifully designed status line for Claude Code"
  homepage "https://github.com/oaooao/ccbar"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oaooao/ccbar/releases/download/v0.2.0/ccbar_0.2.0_darwin_amd64.tar.gz"
      sha256 "04126910a1ef5ca71365160f468abb92dda0f102f524e8785fe675a750093dff"

      define_method(:install) do
        bin.install "ccbar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oaooao/ccbar/releases/download/v0.2.0/ccbar_0.2.0_darwin_arm64.tar.gz"
      sha256 "3430c9195edd3ea88a65691ce153b9a97f1bd4f791a274813959b119d50465b0"

      define_method(:install) do
        bin.install "ccbar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oaooao/ccbar/releases/download/v0.2.0/ccbar_0.2.0_linux_amd64.tar.gz"
      sha256 "6afa1d727f77ce3f681b24ab5940f4f97453ae624904e69521a8ade14ef707b4"
      define_method(:install) do
        bin.install "ccbar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oaooao/ccbar/releases/download/v0.2.0/ccbar_0.2.0_linux_arm64.tar.gz"
      sha256 "9e81c65dcbc35a6aa3e13d86c2bc063edcdf0d08bb2468693196f9b0634005e2"
      define_method(:install) do
        bin.install "ccbar"
      end
    end
  end
end
